### ISSUE TITLE
Add support for Integrated Courses

### ISSUE THREAD

**Issue by dan-and** [ozzieperez/packtpub-library-downloader#16]
Hi,

I would like to raise an issue for adding the integrated courses of Packtpub aswell. 

Patch will come in a few minutes.

**Comment by ozzieperez** [comment]
Hey @dan-and , I don't have any courses in my acct to test with, but it looks good and I'll take your word for it. :shipit:  Way to go! Thanks again bud. 👍

**Comment by dan-and** [comment]
Hey @ozzieperez , 

Thanks for the faith in me. I do bought two integrated  a few month ago, so I was able to test it. However I can only test it on my own account, so the milage of other users may vary. 

As you can see in the code, my changes are rather small, so that I assume that if there is any problem the downloading the integrated courses, the same problem would occur in the videos and ebook section as well. 

I still have a few other functionality ideas for the downloader, so stay tuned. 

Cheers,
Daniel

**Comment by ozzieperez** [comment]
Sounds good, @dan-and. Thanks again! If it's working for you, I'm sure it should be fine. Have an awesome weekend! ✌️ 🚣
