### ISSUE TITLE
Getting Syntax error upon running

### ISSUE THREAD

**Issue by ApCoder123** [ozzieperez/packtpub-library-downloader#3]
@ozzieperez 
I have tried to run this script to download my ebooks, but it is returning a syntax error upon running the script. I am using this to run it:
`python C:\Users\****\Downloads\packtpub-library-downloader-master\packtpub-library-downloader-master\downloader.py -e 'email@email.com' -p 'Password' -f 'pdf,epub,mobi' -d 'C:\Users\****\Desktop\my_ebooks' -c --include-code`
I am running this in the python.exe shell. 
```
File "<stdin>", line 1

    python C:\Users\****\Downloads\packtpub-library-downloader-master\packtpub-library-downloader-master\downloader.py -e 'email@email.com' -p 'Password' -f 'pdf,epub,mobi' -d 'C:\Users\***\Desktop\my_ebooks' -c --include-code
               ^
```

**Comment by ozzieperez** [comment]
Thanks, @ApCoder123. I'll check it out.

**Comment by ozzieperez** [comment]
Hey, @ApCoder123. Try it now. 
Also, now, don't use the single-quotes around the argument values.

**Comment by ApCoder123** [comment]
@ozzieperez I've downloaded the new version and tried to run it (without single quotes) and I'm still getting a syntax error. 
Python Version: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
Code run in python.exe: 
`python C:\Users\****\Downloads\packtpub-library-downloader-master (1)\packtpub-library-downloader-master\downloader.py -e email@email.com -p password -f pdf,epub,mobi -d C:\Users\****\Desktop\my_ebooks -c --include-code`
Error:
```
  File "<stdin>", line 1
    python C:\Users\****\Downloads\packtpub-library-downloader-master (1)\packtpub-library-downloader-master\downloader.py -e email@email.com -p password -f pdf,epub,mobi -d C:\Users\****\Desktop\my_ebooks -c --include-code
           ^
SyntaxError: invalid syntax
```

**Comment by ApCoder123** [comment]
Please ignore my previous comment. It turns out I just hadn't installed the dependencies. Thanks for your help @ozzieperez

**Comment by ozzieperez** [comment]
Glad it's working now @ApCoder123, and thanks for reporting this bug! ✌️
