### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by LucidSeed** [ozzieperez/packtpub-library-downloader#33]
After Inserting #27 to fix the Page looping, I got working on Python 3.7 by;

inserting on Line 8;

`from importlib import reload`

and commenting out Line 383;

 `#   sys.setdefaultencoding('utf8')`

Thanks for creating this script.. makes life soo much easier

**Comment by n31l** [comment]
Just seen the pull request which covers everything I mentioned, please excuse, new to the whole GitHub thing.

**Comment by LucidSeed** [comment]
Just seen the pull request which covers everything I mentioned, please excuse, new to the whole GitHub thing.
