### ISSUE TITLE
Found 0 books, parse issue???

### ISSUE THREAD

**Issue by cking24343** [ozzieperez/packtpub-library-downloader#39]
I have downloaded the script and have tried executing it. It does show me as being 'Logged in successfully!' however the number of books that it shows is still 0. When looking at the script in Atom I can see that you are parsing via the XPath based on div id, but when looking at the page in the browser it appears that that is no longer the correct structure? I assume packtpub has updated there site and now the script is unable to parse it correctly, can anyone confirm this? Am I missing somethings?

**Comment by KillerBabouin** [comment]
Hi Cking,

Already opened on the previous issue thread. ;-)

**Comment by cking24343** [comment]
Yeah I realize that shortly after and when scrolling down to the bottom initially that thread didn't look like it was related. Just honestly forgot to comment on this one or close it out. I'll wait and see come Friday if somebody has a solution, thanks for the reminder

**Comment by lmbringas** [comment]
Hi @cking24343 If you still want to download your books https://github.com/lmbringas/packtpub-downloader
