### ISSUE TITLE
python 3 versus python 2 

### ISSUE THREAD

**Issue by dan-and** [ozzieperez/packtpub-library-downloader#6]
Just a style issue: 

downloader.py's STDOUT prints of the the Book-Title does have a "b" prefix and single-quotes when using python 3. Using python 2.7 it's just the plain title name. 

Is not a problem with directory names where the title is used as well. 

python 3.5: 
(Pdb) title
'HTML5 and CSS3 Responsive Web Design Cookbook'
(Pdb) print(title.encode(sys.stdout.encoding, errors='replace'))
b'HTML5 and CSS3 Responsive Web Design Cookbook'
(Pdb)

Python 2.7:
(Pdb) title
'MongoDB Cookbook'
(Pdb) print(title.encode(sys.stdout.encoding, errors='replace'))
MongoDB Cookbook
(Pdb)

**Comment by ozzieperez** [comment]
Thanks. I checked in the fix. 
https://github.com/ozzieperez/packtpub-library-downloader/commit/f9598656d46357a4736972925585c875e4963cfc#diff-236012c1e2500a3dc7ae7ca0a6dcd51e
